# RuboCop configuration for Ruby 3.3+ with RBS Inline support
inherit_from: .rubocop.yml

plugins:
  - rubocop-rbs_inline

# ========= RBS ===========
Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: method_type_signature
  Exclude:
    - 'spec/**/*'
Style/RbsInline/UntypedInstanceVariable:
  Exclude:
    - 'lib/structured_params/params.rb'
    - 'lib/structured_params.rb'

Style/RbsInline/RequireRbsInlineComment:
  Exclude:
    - 'spec/**/*'
