plugins:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rbs_inline
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Layout/LeadingCommentSpace:
  Enabled: false

# ========= RSpec ===========
RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 15

# ========= Metrics =========
Metrics/ClassLength:
  Max: 150
