plugins:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rbs_inline

AllCops:
  NewCops: enable

Layout/LeadingCommentSpace:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5
