name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} - Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test with latest patch versions
          - ruby: '3.2'
            rails: '~> 7.2.0'
          - ruby: '3.3'
            rails: '~> 7.2.0'
          - ruby: '3.4'
            rails: '~> 7.2.0'
          - ruby: '3.2'
            rails: '~> 8.0.0'
          - ruby: '3.3'
            rails: '~> 8.0.0'
          - ruby: '3.4'
            rails: '~> 8.0.0'

    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
    - name: Set Rails version
      run: |
        echo "RAILS_VERSION=${{ matrix.rails }}" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3
      env:
        RAILS_VERSION: ${{ matrix.rails }}
    - name: Run the default task
      run: bundle exec rake
